export const ACTIONS = 'ACTIONS';
export const ACTION_LOAD_WELLBORE_PLOTS = 'ACTION_LOAD_WELLBORE_PLOTS';
export const ACTION_LOAD_WELLBORE_PLOTS_SUCCESS = 'ACTION_LOAD_WELLBORE_PLOTS_SUCCESS';
export const ACTION_LOAD_WELLBORE_PLOTS_FAIL = 'ACTION_LOAD_WELLBORE_PLOTS_FAIL';

export const ACTION_LOAD = 'ACTION_LOAD';
export const ACTION_LOAD_SUCCESS = 'ACTION_LOAD_SUCCESS';
export const ACTION_LOAD_FAIL = 'ACTION_LOAD_LOG_FAIL';

export const ACTION_UPDATE_WELLBORE_SELECTED_WELLS = 'ACTION_UPDATE_WELLBORE_SELECTED_WELLS';
export const ACTION_UPDATE_WELLBORE_SELECTED_LOGS = 'ACTION_UPDATE_WELLBORE_SELECTED_LOGS';
export const ACTION_UPDATE_WELLBORE_SELECTED_FORMATIONS = 'ACTION_UPDATE_WELLBORE_SELECTED_FORMATIONS';

export const ACTION_LOAD_HISTOGRAM_PLOTS = 'ACTION_LOAD_HISTOGRAM_PLOTS';
export const ACTION_LOAD_HISTOGRAM_PLOTS_SUCCESS = 'ACTION_LOAD_HISTOGRAM_PLOTS_SUCCESS';
export const ACTION_LOAD_HISTOGRAM_PLOTS_FAIL = 'ACTION_LOAD_HISTOGRAM_PLOTS_FAIL';



export const ACTION_UPDATE_HISTOGRAM_SELECTED_WELLS = 'ACTION_UPDATE_HISTOGRAM_SELECTED_WELLS';
export const ACTION_UPDATE_HISTOGRAM_SELECTED_LOGS = 'ACTION_UPDATE_HISTOGRAM_SELECTED_LOGS';
export const ACTION_UPDATE_HISTOGRAM_SELECTED_FORMATIONS = 'ACTION_UPDATE_HISTOGRAM_SELECTED_FORMATIONS';